name: build-linux-static
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get -qq install autoconf automake musl-tools libsdl2-dev
      - run: autoreconf -i
      - run: ./configure CC=musl-gcc CPPFLAGS=-I/usr/include/x86_64-linux-gnu LDFLAGS=-static
      - run: make
