name: Main
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup CMake and vcpkg
        uses: lukka/get-cmake@latest
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: default
          buildPreset: ninja-debug
