name: Main
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: List the files in the repository
        run: ls ${{ github.workspace }}
