name: Main
on: [push]
jobs:
  Build:
    strategy:
      matrix:
        os:
          - windows
          - ubuntu
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup CMake and vcpkg
        uses: lukka/get-cmake@latest
      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
      - if: ${{ matrix.os == 'ubuntu' }}
        name: Install Linux packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          version: 1.0
          packages: >-
            libxinerama-dev
            libxcursor-dev
            xorg-dev
            libglu1-mesa-dev
            pkg-config
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: default
          buildPreset: debug
